# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stablenet.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import learn
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(430, 371)
        self.model_type = "PPO"
        self.time_steps = 25000
        self.show_game = False

        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 100, 197, 176))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.RunLearning = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RunLearning.setObjectName("RunLearning")
        self.RunLearning.clicked.connect(self.run_game)
        self.verticalLayout_3.addWidget(self.RunLearning)

        self.EndLearning = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.EndLearning.clicked.connect(self.end_game)
        self.verticalLayout_3.addWidget(self.EndLearning)

        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(11)
        self.formLayout.setObjectName("formLayout")
        self.Timesteplabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Timesteplabel.setObjectName("Timesteplabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole, self.Timesteplabel)
        self.TimeSteps = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.TimeSteps.setMinimum(10000)
        self.TimeSteps.setMaximum(1000000)
        self.TimeSteps.setSingleStep(5000)
        self.TimeSteps.setProperty("value", 25000)
        self.TimeSteps.setObjectName("TimeSteps")

        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.TimeSteps)
        self.mtypelabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.mtypelabel.setObjectName("mtypelabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mtypelabel)
        self.ModelType = QtWidgets.QVBoxLayout()
        self.ModelType.setObjectName("ModelType")

        self.PPO = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.PPO.setChecked(True)
        self.PPO.setObjectName("PPO")
        self.PPO.toggled.connect(self.set_ppo)
        self.ModelType.addWidget(self.PPO)

        self.A2C = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.A2C.setObjectName("A2C")
        self.A2C.toggled.connect(self.set_a2c)
        self.ModelType.addWidget(self.A2C)

        self.DQN = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.DQN.setObjectName("DQN")
        self.DQN.toggled.connect(self.set_dqn)
        self.ModelType.addWidget(self.DQN)

        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.ModelType)
        self.showgame = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.showgame.setText("")
        self.showgame.setObjectName("showgame")
        self.showgame.stateChanged.connect(self.set_showgame)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.showgame)
        self.showgamelabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.showgamelabel.setObjectName("showgamelabel")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.showgamelabel
        )
        self.verticalLayout_3.addLayout(self.formLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.RunLearning.setText(_translate("Dialog", "RUN LEARN ALGORITHM"))
        self.EndLearning.setText(_translate("Dialog", "END LEARN ALGORITHM"))
        self.Timesteplabel.setText(_translate("Dialog", "Timesteps"))
        self.mtypelabel.setText(_translate("Dialog", "Model type"))
        self.PPO.setText(_translate("Dialog", "PPO"))
        self.A2C.setText(_translate("Dialog", "A2C"))
        self.DQN.setText(_translate("Dialog", "DQN"))
        self.showgamelabel.setText(_translate("Dialog", "Show Game"))

    def set_showgame(self, state):
        self.show_game = state == QtCore.Qt.Checked

    def set_ppo(self):
        self.model_type = "PPO"

    def set_a2c(self):
        self.model_type = "A2C"

    def set_dqn(self):
        self.model_type = "DQN"

    def run_game(self):
        model, total_timesteps = learn.initialize_model(self.model_type)
        timestep_interval = self.TimeSteps.Value()
        while True:
            learn.train_model(model, timestep_interval)
            total_timesteps += timestep_interval
            model.save(f"models/{self.model_type}/{total_timesteps}")
            if self.show_game:
                learn.show_game(model)

    def end_game(self):
        pass


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
